spring:
  config:
    import:
      - classpath:/application-jwt.yml
      - classpath:/application-oauth.yml

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/.h2/MyPetFinder
#    url: jdbc:h2:tcp://localhost/~/MyPetFinder
    username: sa
    password: 1234

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mypetfinder
#    username: root
#    password: 1234


  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: true


#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect

#server:
#  port: 8081
